version: "3"
services:
  postgres_container:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DATABASE: "postgres"
    ports:
      - 5432:5432
    networks:
      - diary_net

  spring_container:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - postgres_container
    networks:
      - diary_net

networks:
  diary_net:
    external: True