#spring.application.name=MUSIC-IN-MY-DIARY-SPRING
spring:
  application:
    name: MUSIC-IN-MY-DIARY-SPRING

  datasource:
    hikari:
      maximum-pool-size: 4
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/diary
    username: postgres
    password: postgres

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true